### PR TITLE
Transition to CMake from waf

### LINKED ISSUE #8: Support Cmake

### PR DESCRIPTION
**Pull request by r9y9**
Follow up for #14

Fixes #8 

## CMake changes from #14

-  Support pkg-config
- Support install
- Fix for semantic versioning
- Fix project name to "hts_engine_API" for compat. We may want to use
HTSEngine in the future though.
- Library versioning
- Two targets: hts engine library and command line binary
- Do not hard-code static

## Breaking 

waf is no longer supported

## TODOS

- [x] Fix travis
- [x] Fix appveyor
- [x] Setup github actions

### CODE REVIEW

**Comment by r9y9** [comment]
cc: @SeleDreams I've made some changes to your cmake config. Please check the items in the PR description. 

I removed the hard-coded STATIC in `add_libary`. If you want to build a static library, please set `BUILD_SHARED_LIBS=OFF` like:

```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
```

**Comment by SeleDreams** [comment]
> cc: @SeleDreams I've made some changes to your cmake config. Please check the items in the PR description.
> 
> I removed the hard-coded STATIC in `add_libary`. If you want to build a static library, please set `BUILD_SHARED_LIBS=OFF` like:
> 
> ```
> cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
> ```

I see, no problem, I myself thought the static hardcoded was maybe not the best idea. I just originally wanted to make something simple to work with, adjusting the edited cmake of sinsy for it won't be hard (I modified sinsy on my local repo to use hts_engine as a submodule and include it directly from the cmake basically making the build process not rely of it being installed, which is better for windows

**Comment by SeleDreams** [comment]
By the way, it was maybe better to keep the ${PROJECT_NAME} variable for add_library etc, since it allowed cmake to automatically account for changes in the project name if it ever changes

**Comment by r9y9** [comment]
Thanks for the comment. I kept the use of ${PROJECT_NAME} in the CMakeLists.txt.

**Comment by r9y9** [comment]
Finally, all green :) Merging.

**Pull request merged**
